staging:
  hostname:  mysql8062.xserver.jp# デプロイ先のホスト名
  stage: staging
  roles:
    - app
  deploy_path: /var/www/html
  branch: master
  become: einswebsrv_yuuki # デプロイを行うユーザ
production:
  hostname: mysql8062.xserver.j # デプロイ先のホスト名
  stage: production
  roles:
    - app
  deploy_path: /var/www/html
  branch: master
  become: einswebsrv_yuuki # デプロイを行うユーザ